remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings
minima:
  skin: dark
title: Floe Foxon  –  Scientist · Analyst · Programmer # name of the site
author: Floe Foxon
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
